import { createStrings } from '@fluvy/core';

export const s = createStrings({
  en: {
    title: 'Openings & motion',
    title_short: 'Openings',
    sensor_one: '1 sensor',
    sensors: '{count} sensors',
    room_one: '1 room',
    rooms: '{count} rooms',
    open_one: '1 open',
    open_many: '{count} open',
    alert_one: '1 alert',
    alert_many: '{count} alerts',
    all_clear: 'All clear',
    all_sensors: 'All sensors',
    more: '{count} more',
    less: 'Show less',
    detected: 'Detected',
    clear: 'Clear',
    wet: 'Wet',
    dry: 'Dry',
    problem: 'Problem',
    ok: 'OK',
    'editor.max_rows': 'Rows before "All sensors"',
  },
  es: {
    title: 'Aperturas y movimiento',
    title_short: 'Aperturas',
    sensor_one: '1 sensor',
    sensors: '{count} sensores',
    room_one: '1 estancia',
    rooms: '{count} estancias',
    open_one: '1 abierto',
    open_many: '{count} abiertos',
    alert_one: '1 alerta',
    alert_many: '{count} alertas',
    all_clear: 'Todo bien',
    all_sensors: 'Todos los sensores',
    more: '{count} más',
    less: 'Ver menos',
    detected: 'Detectado',
    clear: 'Inactivo',
    wet: 'Mojado',
    dry: 'Seco',
    problem: 'Problema',
    ok: 'Normal',
    'editor.max_rows': 'Filas antes de «Todos los sensores»',
  },
});
