// Generated by scripts/community.ts from the files beside it — do not edit; add a file and rebuild.
import type { PaletteFile } from '../file.js';

/** The palettes shared with every house, in the order of their names. */
export const COMMUNITY_PALETTES: readonly PaletteFile[] = [
  {
    fluvy_palette: 1,
    name: 'citrus',
    title: 'Citrus',
    author: 'Fluvy',
    description: 'Electric orange, solid fills, a blue highlight for you and today.',
    palette: {
      character: 'vivid',
      base: 'neutral',
      accent: '#ff8a00',
      fill: 'solid',
      highlight: '#2f6df6',
    },
  },
  {
    fluvy_palette: 1,
    name: 'moss',
    title: 'Moss',
    author: 'Fluvy',
    description: 'A soft moss green over warm paper: the first palette shared with the house.',
    palette: {
      character: 'soft',
      base: 'warm',
      accent: '#4f7a4a',
    },
  },
  {
    fluvy_palette: 1,
    name: 'plum',
    title: 'Plum',
    author: 'Fluvy',
    description: 'A quiet plum over cool grey, for rooms that read at night.',
    palette: {
      character: 'soft',
      base: 'cool',
      accent: '#7a4f8a',
    },
  },
];
