import { createStrings } from '@fluvy/core';

/**
 * The settings panel's words. Palette names are the product's and stay as they are in every language; the
 * Spanish follows Home Assistant's own ("panel" for a dashboard).
 */
export const s = createStrings({
  en: {
    title: 'Fluvy',
    subtitle: 'Theme and cards',
    menu: 'Open the menu',
    'tab.appearance': 'Appearance',
    'tab.scope': 'Scope',
    'tab.dashboard': 'Dashboard',
    'tab.preferences': 'Preferences',
    'tab.about': 'About',
    'palette.title': 'Palette',
    'palette.house': 'The house’s look',
    'palette.own': 'Your own look',
    'palette.pastel': 'Pastel',
    'palette.electric': 'Electric',
    'palette.custom': 'Custom',
    'palette.custom_sub': 'Any accent, contrasts checked',
    'custom.title': 'Your palette',
    'custom.sub': 'Pick an accent; the rest follows',
    'custom.character': 'Style',
    'custom.soft': 'Pastel',
    'custom.vivid': 'Electric',
    'custom.base': 'Ground',
    'custom.warm': 'Warm',
    'custom.neutral': 'Neutral',
    'custom.cool': 'Cool',
    'custom.fill': 'When on',
    'custom.tint': 'Tint',
    'custom.solid': 'Solid',
    'custom.accent': 'Accent',
    'custom.hex': 'Any colour',
    'custom.pick': 'Pick a colour',
    'custom.highlight': 'Highlight',
    'custom.none': 'None',
    'custom.highlight_sub':
      'A second colour for you and for now: your avatar, today in the calendar, the open tab',
    'shape.title': 'Shape',
    'shape.sub': 'The corners of cards, tiles and buttons',
    'shape.soft': 'Soft',
    'shape.round': 'Round',
    'shape.crisp': 'Crisp',
    'pills.title': 'Buttons',
    'pills.sub': 'Chips, tabs and badges',
    'pills.round': 'Pill',
    'pills.soft': 'Soft',
    'pills.crisp': 'Crisp',
    'pills.size_round': 'Full',
    'pills.size_soft': '12',
    'pills.size_crisp': '6',
    'preview.title': 'Preview',
    'preview.sub': 'Your cards with this look',
    'preview.living': 'Living room',
    'preview.kitchen': 'Kitchen',
    'preview.bedroom': 'Bedroom',
    'preview.blinds': 'Blinds',
    'preview.temperature': 'Temperature',
    'preview.solar': 'Solar',
    'preview.grid': 'Grid',
    'preview.battery': 'Battery',
    'preview.app': 'Try it on the whole app',
    'preview.app_sub': 'Until you apply or leave',
    'apply.house': 'Apply to the house',
    'apply.me': 'Only for me',
    'apply.mine': 'Apply for me',
    'apply.discard': 'Discard',
    'apply.region': 'Changes not saved yet',
    'apply.save': 'Save',
    'apply.changes': '{n} changes',
    'apply.trying': 'On the whole app',
    'apply.stop': 'Stop',
    'apply.back': 'Use the house’s look',
    'apply.back_sub': 'You are using your own palette',
    'scope.title': 'Where the look applies',
    'scope.only': 'Only',
    'scope.dashboards': 'Dashboards',
    'scope.everywhere': 'Everywhere',
    'scope.ha': 'Home Assistant',
    'scope.list': 'Dashboards that wear it',
    'scope.list_auto': 'Automatic: those whose address starts with fluvy',
    'scope.list_chosen': '{n} chosen',
    'scope.overview': 'Overview',
    'scope.frame': 'Floating frame',
    'scope.frame_sub': 'The app floats on wide screens',
    'scope.icons': 'Our icons in the menus',
    'scope.icons_sub': 'The sidebar and Settings; off keeps Home Assistant’s',
    'scope.activity': 'Our Activity view',
    'scope.activity_sub': 'A day at a glance, with a time rail; off keeps Home Assistant’s',
    'scope.history': 'Our History view',
    'scope.history_sub':
      'Curves you can read by hand, with the states under them; off keeps Home Assistant’s',
    'scope.admin_only': 'Only an administrator can change this',
    'scope.theme_profile': 'Your profile uses the Fluvy theme',
    'scope.theme_profile_sub':
      'So Home Assistant wears it on every page. With the default theme, only these dashboards do.',
    'scope.theme_house': 'Home Assistant’s default theme is Fluvy',
    'scope.theme_house_sub':
      'So every page wears it, for everyone. With Home Assistant’s theme, only these dashboards do.',
    'scope.theme_house_guest':
      'So every page wears it. An administrator can change the default theme.',
    'scope.theme_use': 'Use the default theme',
    'scope.theme_use_ha': 'Use Home Assistant’s theme',
    'scope.theme_other': 'Home Assistant wears another theme',
    'scope.theme_other_sub':
      'Your theme is {theme}, so Home Assistant keeps it and Fluvy stays on its dashboards. With the Fluvy theme, it reaches every page.',
    'scope.theme_use_fluvy': 'Use the Fluvy theme',
    'scope.summary_dashboards': 'only on dashboards',
    'scope.summary_everywhere': 'everywhere',
    'dashboard.title': 'Automatic dashboard',
    'dashboard.sub': 'Built from your house',
    'dashboard.missing': 'Not created yet',
    'dashboard.create': 'Create it',
    'dashboard.creating': 'Creating it…',
    'dashboard.create_sub': 'Areas, lights, climate, energy and more',
    'dashboard.views': 'Views',
    'dashboard.always': 'Always',
    'dashboard.cards': 'Cards',
    'dashboard.cards_sub': 'How the dashboard draws them',
    'dashboard.preview_sub':
      'Lights, a thermostat and the energy flow, as the dashboard will draw them',
    'dashboard.thermostat': 'Thermostats',
    'dashboard.dial': 'Dial',
    'dashboard.compact': 'Compact',
    'dashboard.ruler': 'Ruler',
    'dashboard.tiles': 'Lights',
    'dashboard.large': 'Large',
    'dashboard.rows': 'Rows',
    'dashboard.flow': 'Energy flow',
    'dashboard.ribbons': 'Ribbons',
    'dashboard.rail': 'Rail',
    'dashboard.legs': 'Lines',
    'pref.title': 'Just for you',
    'pref.sub': 'These follow you on every device',
    'pref.language': 'Language',
    'pref.auto': 'Automatic',
    'pref.reduce': 'Reduce motion',
    'pref.reduce_sub': 'Always, whatever the device asks',
    'pref.haptics': 'Haptics',
    'pref.haptics_sub': 'A tap you can feel in the app',
    'pref.activity_card': 'Activity on a card',
    'pref.activity_card_sub': 'The timeline in its own box, like the dashboards; off, on the page',
    'about.title': 'Fluvy',
    'about.version': 'Version {version}',
    'about.look': 'Look in use',
    'about.shell': 'Home Assistant pages',
    'about.shell_value': '{styled} of {total} styled',
    'about.shell_off': 'Not styled on this screen',
    'about.file': 'Settings file',
    'about.file_sub': 'Move this setup to another house',
    'about.export': 'Export',
    'about.import': 'Import',
    'about.reset': 'Reset the house’s settings',
    'about.reset_sub': 'Back to {look}, {scope}',
    'about.reset_armed': 'Tap again to reset',
    'about.reset_cancels': 'Cancels in 4 seconds',
    'about.reset_done': 'House settings reset',
    'about.imported': 'Settings imported',
    'about.invalid': 'That file holds no Fluvy settings',
    'change.on': 'On',
    'change.off': 'Off',
    'change.dashboards': 'Only on dashboards',
    'change.everywhere': 'On all of Home Assistant',
    saved: 'Saved',
  },
  es: {
    title: 'Fluvy',
    subtitle: 'Tema y tarjetas',
    menu: 'Abrir el menú',
    'tab.appearance': 'Apariencia',
    'tab.scope': 'Alcance',
    'tab.dashboard': 'Panel',
    'tab.preferences': 'Preferencias',
    'tab.about': 'Acerca de',
    'palette.title': 'Paleta',
    'palette.house': 'El aspecto de la casa',
    'palette.own': 'Tu propio aspecto',
    'palette.pastel': 'Pastel',
    'palette.electric': 'Eléctricas',
    'palette.custom': 'Personalizada',
    'palette.custom_sub': 'Cualquier acento, contrastes comprobados',
    'custom.title': 'Tu paleta',
    'custom.sub': 'Elige un acento; el resto lo sigue',
    'custom.character': 'Estilo',
    'custom.soft': 'Pastel',
    'custom.vivid': 'Eléctrico',
    'custom.base': 'Fondo',
    'custom.warm': 'Cálido',
    'custom.neutral': 'Neutro',
    'custom.cool': 'Frío',
    'custom.fill': 'Encendido',
    'custom.tint': 'Tinte',
    'custom.solid': 'Sólido',
    'custom.accent': 'Acento',
    'custom.hex': 'Cualquier color',
    'custom.pick': 'Elegir un color',
    'custom.highlight': 'Resalte',
    'custom.none': 'Ninguno',
    'custom.highlight_sub':
      'Un segundo color para ti y para ahora: tu avatar, hoy en el calendario, la pestaña abierta',
    'shape.title': 'Forma',
    'shape.sub': 'Las esquinas de tarjetas, mosaicos y botones',
    'shape.soft': 'Suave',
    'shape.round': 'Redonda',
    'shape.crisp': 'Precisa',
    'pills.title': 'Botones',
    'pills.sub': 'Chips, pestañas y etiquetas',
    'pills.round': 'Píldora',
    'pills.soft': 'Suave',
    'pills.crisp': 'Preciso',
    'pills.size_round': 'Completo',
    'pills.size_soft': '12',
    'pills.size_crisp': '6',
    'preview.title': 'Vista previa',
    'preview.sub': 'Tus tarjetas con este aspecto',
    'preview.living': 'Salón',
    'preview.kitchen': 'Cocina',
    'preview.bedroom': 'Dormitorio',
    'preview.blinds': 'Persianas',
    'preview.temperature': 'Temperatura',
    'preview.solar': 'Solar',
    'preview.grid': 'Red',
    'preview.battery': 'Batería',
    'preview.app': 'Probarlo en toda la app',
    'preview.app_sub': 'Hasta que apliques o salgas',
    'apply.house': 'Aplicar a la casa',
    'apply.me': 'Solo para mí',
    'apply.mine': 'Aplicar para mí',
    'apply.discard': 'Descartar',
    'apply.region': 'Cambios sin guardar',
    'apply.save': 'Guardar',
    'apply.changes': '{n} cambios',
    'apply.trying': 'En toda la app',
    'apply.stop': 'Parar',
    'apply.back': 'Usar el de la casa',
    'apply.back_sub': 'Estás usando tu propia paleta',
    'scope.title': 'Dónde se aplica',
    'scope.only': 'Solo',
    'scope.dashboards': 'Paneles',
    'scope.everywhere': 'En todo',
    'scope.ha': 'Home Assistant',
    'scope.list': 'Paneles que lo llevan',
    'scope.list_auto': 'Automático: los que tienen una dirección que empieza por fluvy',
    'scope.list_chosen': '{n} elegidos',
    'scope.overview': 'Resumen',
    'scope.frame': 'Marco flotante',
    'scope.frame_sub': 'La app flota en pantallas anchas',
    'scope.icons': 'Nuestros iconos en los menús',
    'scope.icons_sub': 'La barra lateral y Ajustes; apagado deja los de Home Assistant',
    'scope.activity': 'Nuestra vista de Actividad',
    'scope.activity_sub':
      'El día de un vistazo, con carril de tiempo; apagada deja la de Home Assistant',
    'scope.history': 'Nuestra vista de Historial',
    'scope.history_sub':
      'Curvas que se leen con el dedo, y debajo los estados; apagada deja la de Home Assistant',
    'scope.admin_only': 'Solo un administrador puede cambiarlo',
    'scope.theme_profile': 'Tu perfil usa el tema Fluvy',
    'scope.theme_profile_sub':
      'Por eso Home Assistant lo lleva en todas las páginas. Con el tema por defecto, solo lo llevan estos paneles.',
    'scope.theme_house': 'El tema por defecto de Home Assistant es Fluvy',
    'scope.theme_house_sub':
      'Por eso todas las páginas lo llevan, para todos. Con el tema de Home Assistant, solo lo llevan estos paneles.',
    'scope.theme_house_guest':
      'Por eso todas las páginas lo llevan. Un administrador puede cambiar el tema por defecto.',
    'scope.theme_use': 'Usar el tema por defecto',
    'scope.theme_use_ha': 'Usar el tema de Home Assistant',
    'scope.theme_other': 'Home Assistant lleva otro tema',
    'scope.theme_other_sub':
      'Tu tema es {theme}: Home Assistant lo mantiene y Fluvy se queda en sus paneles. Con el tema Fluvy llega a todas las páginas.',
    'scope.theme_use_fluvy': 'Usar el tema Fluvy',
    'scope.summary_dashboards': 'solo en los paneles',
    'scope.summary_everywhere': 'en todo Home Assistant',
    'dashboard.title': 'Panel automático',
    'dashboard.sub': 'Hecho a partir de tu casa',
    'dashboard.missing': 'Aún no está creado',
    'dashboard.create': 'Crearlo',
    'dashboard.creating': 'Creándolo…',
    'dashboard.create_sub': 'Estancias, luces, clima, energía y más',
    'dashboard.views': 'Vistas',
    'dashboard.always': 'Siempre',
    'dashboard.cards': 'Tarjetas',
    'dashboard.cards_sub': 'Cómo las dibuja el panel',
    'dashboard.preview_sub':
      'Luces, un termostato y el flujo de energía, como los dibujará el panel',
    'dashboard.thermostat': 'Termostatos',
    'dashboard.dial': 'Dial',
    'dashboard.compact': 'Compacto',
    'dashboard.ruler': 'Regla',
    'dashboard.tiles': 'Luces',
    'dashboard.large': 'Grandes',
    'dashboard.rows': 'Filas',
    'dashboard.flow': 'Flujo de energía',
    'dashboard.ribbons': 'Cintas',
    'dashboard.rail': 'Carril',
    'dashboard.legs': 'Líneas',
    'pref.title': 'Solo para ti',
    'pref.sub': 'Te siguen en todos tus dispositivos',
    'pref.language': 'Idioma',
    'pref.auto': 'Automático',
    'pref.reduce': 'Reducir movimiento',
    'pref.reduce_sub': 'Siempre, pida lo que pida el dispositivo',
    'pref.haptics': 'Vibración',
    'pref.haptics_sub': 'Un toque que se siente en la app',
    'pref.activity_card': 'Actividad en una tarjeta',
    'pref.activity_card_sub':
      'La línea de tiempo en su caja, como en los dashboards; apagado, sobre la página',
    'about.title': 'Fluvy',
    'about.version': 'Versión {version}',
    'about.look': 'Aspecto en uso',
    'about.shell': 'Páginas de Home Assistant',
    'about.shell_value': '{styled} de {total} con estilo',
    'about.shell_off': 'Sin estilo en esta pantalla',
    'about.file': 'Archivo de ajustes',
    'about.file_sub': 'Lleva esta configuración a otra casa',
    'about.export': 'Exportar',
    'about.import': 'Importar',
    'about.reset': 'Restablecer los ajustes',
    'about.reset_sub': 'Vuelve a {look}, {scope}',
    'about.reset_armed': 'Toca otra vez para restablecer',
    'about.reset_cancels': 'Se cancela en 4 segundos',
    'about.reset_done': 'Ajustes de la casa restablecidos',
    'about.imported': 'Ajustes importados',
    'about.invalid': 'Ese archivo no contiene ajustes de Fluvy',
    'change.on': 'Sí',
    'change.off': 'No',
    'change.dashboards': 'Solo en los paneles',
    'change.everywhere': 'En todo Home Assistant',
    saved: 'Guardado',
  },
});
