/* Generated by tools/icons/mdi-map.mjs from tools/icons/mdi-glyphs.json — do not edit. */
/** Home Assistant's Material icons (a key of their path, `pathKey`) and the glyph of ours that replaces each. */
export const MDI_GLYPHS: Readonly<Record<string, string>> = {
  '1ll0t8a': 'pencil', // mdiPencil
  '13495xt': 'pencil', // mdiPencilOutline
  '1ml9lok': 'dots-vertical', // mdiDotsVertical
  '1efswwu': 'dots', // mdiDotsHorizontal
  qmehzy: 'undo', // mdiUndo
  oi7aih: 'redo', // mdiRedo
  '1xs50qk': 'help', // mdiHelpCircle
  '3pqqkb': 'help', // mdiHelpCircleOutline
  '1id7jhz': 'list', // mdiFormatListBulletedTriangle
  xccdww: 'list', // mdiFormatListBulleted
  '17y2p9r': 'code', // mdiCodeBraces
  '1wwrqkn': 'grid', // mdiViewDashboard
  ibzxx9: 'file-code', // mdiFileMultiple
  '1lf8tvf': 'search', // mdiMagnify
  '1wfen6z': 'chat', // mdiCommentProcessingOutline
  bb97gc: 'auto', // mdiRefresh
  '1wcw8rc': 'box', // mdiShape
  '1rf9uns': 'plus', // mdiPlus
  '18ek9gd': 'devices', // mdiDevices
  '6fb7v1': 'automation', // mdiRobot
  '1mkctkm': 'rooms', // mdiSofa
  '14gl4hb': 'person', // mdiAccount
  '1nwjq21': 'close', // mdiClose
  '11uvra0': 'gear', // mdiCog
  '1rtxfyu': 'gear', // mdiCogOutline
  fkypx6: 'bell', // mdiBell
  i10pa5: 'bell', // mdiBellOutline
  '11k9wmx': 'info', // mdiInformationOutline
  '10pghh5': 'copy', // mdiContentCopy
  qcov39: 'trash', // mdiDelete
  '16kexay': 'trash', // mdiDeleteOutline
  j490ks: 'download', // mdiDownload
  i6tqy1: 'upload', // mdiUpload
  w7mwa5: 'check', // mdiCheck
  '1wkyb3s': 'menu', // mdiMenu
  '17q1r5b': 'chevron-left', // mdiArrowLeft
  '5e7j0g': 'chevron', // mdiArrowRight
  '5k0pfo': 'chevron-left', // mdiChevronLeft
  '1mz7ff4': 'chevron', // mdiChevronRight
};
