/**
 * The automatic dashboard reads a house by the words people name things with, in every language Fluvy ships at
 * once (a house is named in its own language, not the UI's). This writes those words, from every catalogue's
 * `words` table, as the regular expressions `packages/cards/src/strategy/words.generated.ts` exports.
 *
 *   pnpm i18n build       (also part of `pnpm build`); the strategy's tests fail when the file is stale
 *
 * A stem is matched as a substring; a stem may carry a boundary of its own (`pv\b`, `mode$`). `light` matches whole
 * words between separators, `generic` matches the whole name, `place_noise` whole words.
 */
import { writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { catalogueCodes, readCatalogue, ROOT, type Words } from './lib.js';

export const OUT = join(ROOT, 'packages', 'cards', 'src', 'strategy', 'words.generated.ts');

type Shape = 'substring' | 'word' | 'whole' | 'words';

/** Each category's shape, and the constant it becomes. */
const CATEGORIES: ReadonlyArray<{ category: string; name: string; shape: Shape }> = [
  { category: 'light', name: 'LIGHT_WORDS', shape: 'word' },
  { category: 'outdoor', name: 'OUTDOOR', shape: 'substring' },
  { category: 'solar', name: 'SOLAR', shape: 'substring' },
  { category: 'grid', name: 'GRID', shape: 'substring' },
  { category: 'battery', name: 'BATTERY_POWER', shape: 'substring' },
  { category: 'home', name: 'HOME_POWER', shape: 'substring' },
  { category: 'today', name: 'TODAY', shape: 'substring' },
  { category: 'not_appliance', name: 'NOT_APPLIANCE', shape: 'substring' },
  { category: 'generic', name: 'GENERIC', shape: 'whole' },
  { category: 'place_noise', name: 'PLACE_NOISE', shape: 'words' },
];

/** A stem as a regex fragment: escaped, unless it carries regex of its own (a class, a boundary, an anchor). */
const fragment = (stem: string): string =>
  /[\\[\]$^]/.test(stem) ? stem : stem.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

function pattern(stems: readonly string[], shape: Shape): string {
  const alternation = [...new Set(stems)].map(fragment).join('|');
  switch (shape) {
    case 'word':
      return `(^|[\\s_.-])(${alternation})([\\s_.-]|$)`;
    case 'whole':
      return `^(${alternation})$`;
    case 'words':
      return `\\b(${alternation})\\b`;
    default:
      return alternation;
  }
}

export async function generate(): Promise<string> {
  const codes = await catalogueCodes();
  const lists = new Map<string, string[]>();
  for (const code of codes) {
    const words = (await readCatalogue(code))['words'] as Words | undefined;
    for (const { category } of CATEGORIES)
      lists.set(category, [...(lists.get(category) ?? []), ...(words?.[category] ?? [])]);
  }
  const lines = CATEGORIES.map(({ category, name, shape }) => {
    const stems = lists.get(category) ?? [];
    const source = pattern(stems, shape);
    new RegExp(source, 'i'); // a stem that does not compile stops the build here, not in a browser
    const flags = shape === 'words' ? 'gi' : 'i';
    return `/** ${category}: ${stems.length} stems in ${codes.join(', ')}. */\nexport const ${name} = /${source.replace(/\//g, '\\/')}/${flags};`;
  });
  return `// Generated by tools/i18n/src/build.ts from the catalogues' \`words\` tables — do not edit; run \`pnpm i18n build\`.\n\n${lines.join('\n\n')}\n`;
}

if (process.argv[1] && import.meta.url.endsWith(process.argv[1].split('/').pop() ?? '')) {
  const text = await generate();
  await writeFile(OUT, text);
  console.log(`${OUT.replace(ROOT, '.')}: ${CATEGORIES.length} word rules`);
}
