import { RELEASE_VERSION } from '../release.js';
import { GATES } from '../build/derive.js';
import type { Palette, PaletteMode } from '../types.js';
import {
  checkContrast,
  checkStructure,
  type ContrastResult,
  type StructuralResult,
} from './gates.js';

export {
  brandColour,
  checkContrast,
  checkStructure,
  collectHexValues,
  contrastGates,
  type ContrastGate,
  type ContrastResult,
  type StructuralResult,
} from './gates.js';

export interface PaletteReport {
  readonly palette: string;
  readonly mode: PaletteMode;
  readonly contrast: readonly ContrastResult[];
  readonly structural: readonly StructuralResult[];
}

export function buildReports(palettes: readonly Palette[]): readonly PaletteReport[] {
  return palettes.flatMap((palette) =>
    (['light', 'dark'] as const).map((mode) => ({
      palette: palette.name,
      mode,
      contrast: checkContrast(palette[mode]),
      structural: checkStructure(palette, mode),
    })),
  );
}

export function countFailures(reports: readonly PaletteReport[]): number {
  return reports.reduce(
    (total, report) =>
      total +
      report.contrast.filter((entry) => !entry.pass).length +
      report.structural.filter((entry) => !entry.pass).length,
    0,
  );
}

function verdict(pass: boolean, notApplicable?: string): string {
  return notApplicable ? `n/a (${notApplicable})` : pass ? 'pass' : '**FAIL**';
}

export function renderContrastReport(palettes: readonly Palette[]): string {
  const reports = buildReports(palettes);
  const failures = countFailures(reports);

  const lines: string[] = [
    '# Contrast report',
    '',
    `Generated by \`@fluvy/tokens\` v${RELEASE_VERSION}. Every row is enforced by the build:`,
    'a single failure exits non-zero. Gates are never lowered — seeds and derivation move instead.',
    '',
    '| gate | threshold |',
    '| --- | --- |',
    `| text and value inks | ${GATES.text}:1 |`,
    `| icons, large text, domain-state inks | ${GATES.icon}:1 |`,
    `| card against page (light) | ${GATES.cardVsPage}:1 |`,
    `| card against page (dark) | ${GATES.darkCardLift.min * 100}–${GATES.darkCardLift.max * 100} lightness points |`,
    `| hairline against its surface | ${GATES.borderVsCard}:1 |`,
    `| ink on a filled surface | ${GATES.onFill}:1 |`,
    `| graph series separation | ΔE2000 >= ${GATES.graphSeparation} |`,
    `| status and domain-state ink separation | ΔE2000 >= ${GATES.roleSeparation} |`,
    `| domain-state hue spacing | >= ${GATES.stateHueGap}° |`,
    '',
    '## Summary',
    '',
    '| palette | mode | checks | failures |',
    '| --- | --- | ---: | ---: |',
  ];

  for (const report of reports) {
    const total = report.contrast.length + report.structural.length;
    const failed =
      report.contrast.filter((entry) => !entry.pass).length +
      report.structural.filter((entry) => !entry.pass).length;
    lines.push(`| ${report.palette} | ${report.mode} | ${total} | ${failed} |`);
  }

  lines.push('', `**Total failures: ${failures}**`, '');

  for (const report of reports) {
    lines.push(`## ${report.palette} — ${report.mode}`, '');
    lines.push('| pair | foreground | background | ratio | min | result | note |');
    lines.push('| --- | --- | --- | ---: | ---: | --- | --- |');
    for (const entry of report.contrast) {
      lines.push(
        `| \`${entry.id}\` | \`${entry.foreground}\` | \`${entry.background}\` | ${entry.ratio.toFixed(2)} | ${entry.min} | ${verdict(entry.pass)} | ${entry.note ?? ''} |`,
      );
    }
    lines.push('', '| structural check | detail | result |', '| --- | --- | --- |');
    for (const entry of report.structural) {
      lines.push(
        `| \`${entry.id}\` | ${entry.detail} | ${verdict(entry.pass, entry.notApplicable)} |`,
      );
    }
    lines.push('');
  }

  return `${lines.join('\n')}\n`;
}
