#!/usr/bin/env node
/**
 * Writes the table that tells Home Assistant's Material icons (as `ha-svg-icon` draws them: a path) from ours:
 *   node tools/icons/mdi-map.mjs
 * `mdi-glyphs.json` names each Material icon and the glyph that replaces it; the table keeps only a 32-bit key of
 * each path (the paths themselves are not bundled). `@mdi/js` is pinned to the version Home Assistant ships.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import * as mdi from '@mdi/js';
import { pathKey } from '../../packages/core/src/icons/path-key.js';

const map = JSON.parse(readFileSync(new URL('./mdi-glyphs.json', import.meta.url), 'utf8'));
const lines = [
  '/* Generated by tools/icons/mdi-map.mjs from tools/icons/mdi-glyphs.json — do not edit. */',
  "/** Home Assistant's Material icons (a key of their path, `pathKey`) and the glyph of ours that replaces each. */",
  'export const MDI_GLYPHS: Readonly<Record<string, string>> = {',
];
for (const [name, glyph] of Object.entries(map)) {
  const path = mdi[name];
  if (typeof path !== 'string') throw new Error(`no ${name} in @mdi/js`);
  lines.push(`  '${pathKey(path)}': '${glyph}', // ${name}`);
}
lines.push('};');
writeFileSync(
  new URL('../../packages/core/src/icons/mdi.ts', import.meta.url),
  `${lines.join('\n')}\n`,
);
console.log(`${Object.keys(map).length} Material icons → packages/core/src/icons/mdi.ts`);
