/**
 * The words every page of ours needs: its period (today, the presets, the month's arrows, the hours of a day), its
 * sources, and the handful of labels a layer wants. A page spreads them into its own table and adds what is its own.
 */
export const PAGE_WORDS = {
  en: {
    menu: 'Open the menu',
    today: 'Today',
    yesterday: 'Yesterday',
    previous: 'Earlier',
    previous_day: 'Previous day',
    next_day: 'Next day',
    next: 'Later',
    pick: 'Choose dates',
    clear: 'Clear',
    sources: 'Sources',
    download: 'Download',
    apply: 'Show',
    'preset.today': 'Today',
    'preset.yesterday': 'Yesterday',
    'preset.week': 'Last 7 days',
    now: 'now',
    since: 'Since {when}',
    last_day: 'Last 24\u00a0hours',
    hours: 'Hours',
    minutes: 'Minutes',
    end_before_start: 'The end must come after the start',
    period_start: 'Start of the period',
    dates: 'Dates',
    month_prev: 'Previous month',
    month_next: 'Next month',
    back: 'Back',
    close: 'Close',
    done: 'Done',
    period: 'Period',
    days: '{n} days',
    sources_none: 'The sources open inside Home Assistant',
    sources_clear: 'Clear',
    sources_back: 'Back',
    sources_filters: 'filters',
  },
  es: {
    menu: 'Abrir el menú',
    today: 'Hoy',
    yesterday: 'Ayer',
    previous: 'Antes',
    previous_day: 'Día anterior',
    next_day: 'Día siguiente',
    next: 'Después',
    pick: 'Elegir fechas',
    clear: 'Borrar',
    sources: 'Fuentes',
    download: 'Descargar',
    apply: 'Ver',
    'preset.today': 'Hoy',
    'preset.yesterday': 'Ayer',
    'preset.week': 'Últimos 7 días',
    now: 'ahora',
    since: 'Desde {when}',
    last_day: 'Últimas 24\u00a0horas',
    hours: 'Horas',
    minutes: 'Minutos',
    end_before_start: 'El final debe ir después del inicio',
    period_start: 'Empieza el periodo',
    dates: 'Fechas',
    month_prev: 'Mes anterior',
    month_next: 'Mes siguiente',
    back: 'Atrás',
    close: 'Cerrar',
    done: 'Listo',
    period: 'Periodo',
    days: '{n} días',
    sources_none: 'Las fuentes se abren dentro de Home Assistant',
    sources_clear: 'Quitar',
    sources_back: 'Volver',
    sources_filters: 'filtros',
  },
} as const;
