import { createHash } from 'node:crypto';
import {
  brandColorVars,
  haModeVars,
  haSharedVars,
  identityVars,
  RELEASE_VERSION,
  scaleVars,
  THEME_NAME,
  type CssDeclaration,
  type Palette,
  type PaletteModeColors,
  type VarGroup,
} from '@fluvy/tokens';

/**
 * A Home Assistant theme is a flat map of custom properties that the frontend writes inline on
 * an element (no selectors, no `@media`, no `@font-face`). Keys are written WITHOUT the leading
 * `--`; every value must be a YAML string, and both `modes.light` and `modes.dark` have to be
 * declared or the theme is light-only (Home Assistant's theme documentation says the rest).
 *
 * What goes into it is decided in `@fluvy/tokens`: the brand layer (`emit/vars.ts`) and Home Assistant's
 * names grouped by what they style (`ha/groups.ts`). This package only writes and validates the file.
 */

/**
 * The one theme fluvy installs. It carries the default look (Linen, Soft); the palette and shape chosen in
 * fluvy's settings are applied live by the bundle over it (`@fluvy/core` look engine), so a palette never
 * needs a theme of its own.
 */
export { THEME_NAME };

function entries(groups: readonly VarGroup[]): readonly CssDeclaration[] {
  return groups.flatMap((group) => group.declarations);
}

/** Every declaration of one mode, brand layer first so a reader meets our own names before HA's. */
export function modeDeclarations(colors: PaletteModeColors): readonly CssDeclaration[] {
  return entries([...brandColorVars(colors), ...haModeVars(colors)]);
}

/** The top level of the theme: our scale, the mode-independent half of Home Assistant's names, which palette this is. */
export function sharedDeclarations(palette: Palette): readonly CssDeclaration[] {
  return entries([...scaleVars(), ...haSharedVars(), ...identityVars(palette)]);
}

/** YAML double-quoted scalar. Values are hex colours, lengths and font stacks: only `\` and `"` need escaping. */
function quote(value: string): string {
  return `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
}

function key(name: string): string {
  if (!name.startsWith('--')) throw new Error(`Theme variable "${name}" must start with "--"`);
  return name.slice(2);
}

function block(declarations: readonly CssDeclaration[], indent: string): string {
  const seen = new Set<string>();
  const lines: string[] = [];
  for (const [name, value] of declarations) {
    const k = key(name);
    if (seen.has(k)) throw new Error(`Duplicate theme key "${k}"`);
    seen.add(k);
    lines.push(`${indent}${k}: ${quote(value)}`);
  }
  return lines.join('\n');
}

/** The key a deploy reads back from Home Assistant to prove that this very file is the one it serves. */
export const BUILD_KEY = 'fluvy-theme-build';

export function emitThemeYaml(palette: Palette): string {
  const name = THEME_NAME;
  const body = [
    block(sharedDeclarations(palette), '  '),
    '  modes:',
    '    light:',
    block(modeDeclarations(palette.light), '      '),
    '    dark:',
    block(modeDeclarations(palette.dark), '      '),
  ].join('\n');
  // a fingerprint of the declarations: the same tokens give the same stamp, any change a new one
  const stamp = createHash('sha256').update(body).digest('hex').slice(0, 8);
  return [
    `# ${name} v${RELEASE_VERSION} — generated by @fluvy/theme from @fluvy/tokens. Do not edit.`,
    '# Every value is a quoted string; colours are plain #rrggbb because Home Assistant reads them from JavaScript.',
    `# The default look (${palette.title}). fluvy's settings apply any other palette and shape live, over this file.`,
    `${name}:`,
    `  ${BUILD_KEY}: ${quote(stamp)}`,
    body,
    '',
  ].join('\n');
}
