// Generated by tools/i18n/src/build.ts from the catalogues' `words` tables — do not edit; run `pnpm i18n build`.

/** light: 17 stems in de, en, es, fr, it, nl, pt-BR. */
export const LIGHT_WORDS = /(^|[\s_.-])(light|lights|lamp|led|leds|strip|spot|luz|luces|lampara|lámpara|bombilla|foco|focos|plafon|plafón|aplique)([\s_.-]|$)/i;

/** outdoor: 15 stems in de, en, es, fr, it, nl, pt-BR. */
export const OUTDOOR = /porch|garden|outdoor|garage|pool|patio|jard|exterior|porche|terraza|balc|fachada|calle|garaje|piscina/i;

/** solar: 6 stems in de, en, es, fr, it, nl, pt-BR. */
export const SOLAR = /solar|inverter|pv\b|photovolt|inversor|fotovolt/i;

/** grid: 8 stems in de, en, es, fr, it, nl, pt-BR. */
export const GRID = /power_meter|grid|meter|import|net_|contador|red_|_red\b/i;

/** battery: 3 stems in de, en, es, fr, it, nl, pt-BR. */
export const BATTERY_POWER = /battery|storage|bater/i;

/** home: 6 stems in de, en, es, fr, it, nl, pt-BR. */
export const HOME_POWER = /house|home|load|total_consum|casa|consumo_total/i;

/** today: 7 stems in de, en, es, fr, it, nl, pt-BR. */
export const TODAY = /today|daily|day\b|_d$|hoy|dia\b|día/i;

/** not_appliance: 25 stems in de, en, es, fr, it, nl, pt-BR. */
export const NOT_APPLIANCE = /force|timer|holiday|boost|child|lock|enable|mode$|auto$|beep|sound|silent|indicator|led_|_led$|valve|forzar|vacacion|bloqueo|habilit|modo$|valvula|válvula|llave|grifo/i;

/** generic: 30 stems in de, en, es, fr, it, nl, pt-BR. */
export const GENERIC = /^(temperature|humidity|moisture|occupancy|motion|presence|battery|battery level|power|energy|switch|outlet|light|state|status|contact|door|window|leak|water leak|level|temperatura|humedad|movimiento|presencia|bater[ií]a|potencia|energ[ií]a|luz|estado)$/i;

/** place_noise: 15 stems in de, en, es, fr, it, nl, pt-BR. */
export const PLACE_NOISE = /\b(sensor|sensors|temperature|humidity|thermostat|clima|sensores|temperatura|humedad|termostato|de|del|la|el)\b/gi;
