// Generated by tools/i18n/src/build.ts from the catalogues' `words` tables — do not edit; run `pnpm i18n build`.

/** light: 102 stems in de, en, es, fr, it, nl, pt-BR, tr. */
export const LIGHT_WORDS = /(^|[\s_.-])(licht|lichter|lampe|lampen|leuchte|strahler|deckenlicht|deckenleuchte|stehlampe|spot|light|lights|lamp|led|leds|strip|luz|luces|lampara|lámpara|bombilla|foco|focos|plafon|plafón|aplique|lumière|lumiere|lumières|lumieres|lampes|éclairage|eclairage|plafonnier|applique|spots|lampadaire|luce|luci|lampada|lampade|lampadario|faretto|faretti|plafoniera|abat-jour|lichten|verlichting|plafondlamp|staande lamp|luzes|lâmpada|lâmpadas|lampadas|luminária|luminaria|abajur|arandela|ışık|ışığı|ışıklar|ışıkları|isik|isigi|isiklar|isiklari|lamba|lambası|lambasi|lambalar|lambaları|lambalari|aydınlatma|aydınlatması|aydinlatma|aydinlatmasi|ledler|şerit|serit|spotlar|avize|avizesi|aplik|plafonyer)([\s_.-]|$)/i;

/** outdoor: 83 stems in de, en, es, fr, it, nl, pt-BR, tr. */
export const OUTDOOR = /garten|terrasse|balkon|hof|einfahrt|außen|aussen|draußen|draussen|carport|porch|garden|outdoor|garage|pool|patio|jard|exterior|porche|terraza|balc|fachada|calle|garaje|piscina|jardin|balcon|extérieur|exterieur|allée|allee|cour|piscine|abri|giardino|terrazza|terrazzo|balcone|esterno|cortile|vialetto|portico|box auto|tuin|terras|buiten|oprit|schuur|zwembad|veranda|jardim|quintal|varanda|terraço|terraco|área externa|area externa|externo|garagem|edícula|edicula|bahçe|bahce|dış|dis mekan|dışarı|disari|teras|garaj|havuz|avlu|giriş yolu|giris yolu|otopark|çatı|sundurma/i;

/** solar: 34 stems in de, en, es, fr, it, nl, pt-BR, tr. */
export const SOLAR = /wechselrichter|photovoltaik|solar|inverter|pv\b|photovolt|inversor|fotovolt|solaire|onduleur|panneaux|photovolta|solare|fotovoltaico|pannelli|zonnepanelen|omvormer|zonne|pv|painéis|paineis|güneş|gunes|invertör|invertor|fotovoltaik|panel/i;

/** grid: 45 stems in de, en, es, fr, it, nl, pt-BR, tr. */
export const GRID = /netz|zähler|zaehler|bezug|einspeis|power_meter|grid|meter|import|net_|contador|red_|_red\b|réseau|reseau|compteur|linky|soutirage|injection|rete|contatore|prelievo|immissione|net|netstroom|slimme meter|afname|teruglever|rede|medidor|relógio|relogio|consumo da rede|importação|importacao|exportação|exportacao|şebeke|sebeke|sayaç|sayac|ithal|alım\b/i;

/** battery: 20 stems in de, en, es, fr, it, nl, pt-BR, tr. */
export const BATTERY_POWER = /akku|speicher|battery|storage|bater|batterie|accumulateur|stockage|batteria|accumulo|accu|thuisbatterij|batterij|bateria|armazenamento|batarya|pil\b|akü|aku\b|depolama/i;

/** home: 36 stems in de, en, es, fr, it, nl, pt-BR, tr. */
export const HOME_POWER = /haus|wohnung|gesamtverbrauch|hausverbrauch|house|home|load|total_consum|casa|consumo_total|maison|logement|consommation totale|conso|abitazione|consumo totale|consumo casa|huis|woning|totaal verbruik|totaalverbruik|residência|residencia|consumo total|consumo da casa|ev\b|evin\b|toplam tüketim|toplam tuketim|tüketim|tuketim|yük\b|yuk\b|konut/i;

/** today: 30 stems in de, en, es, fr, it, nl, pt-BR, tr. */
export const TODAY = /heute|tages|today|daily|day\b|_d$|hoy|dia\b|día|aujourd|journée|journee|jour|oggi|giornaliero|giornata|giorno|vandaag|dag|hoje|diário|diario|dia|bugün|bugun|günlük|gunluk|gün\b|gun\b/i;

/** not_appliance: 90 stems in de, en, es, fr, it, nl, pt-BR, tr. */
export const NOT_APPLIANCE = /urlaub|kindersicherung|sperre|freigabe|betriebsart|ventil|hahn|force|timer|holiday|boost|child|lock|enable|mode$|auto$|beep|sound|silent|indicator|led_|_led$|valve|forzar|vacacion|bloqueo|habilit|modo$|valvula|válvula|llave|grifo|vacances|sécurité enfant|securite enfant|verrou|vanne|robinet|forçage|forcage|vacanza|blocco bambini|blocco|abilita|valvola|rubinetto|forzatura|modalità|vakantie|kinderslot|vergrendeling|ventiel|kraan|modus|stand|férias|ferias|bloqueio|trava|registro|torneira|modo|zorla|zamanlayıcı|zamanlayici|tatil|güçlendirme|guclendirme|çocuk|cocuk|kilit|etkinleştir|etkinlestir|mod$|modu$|oto$|otomatik$|bip|sessiz|gösterge|gosterge|vana|valf|ses\b|sesi\b/i;

/** generic: 159 stems in de, en, es, fr, it, nl, pt-BR, tr. */
export const GENERIC = /^(temperatur|luftfeuchtigkeit|feuchtigkeit|bewegung|anwesenheit|batterie|leistung|energie|schalter|steckdose|licht|status|zustand|kontakt|tür|tuer|fenster|leck|füllstand|fuellstand|temperature|humidity|moisture|occupancy|motion|presence|battery|battery level|power|energy|switch|outlet|light|state|contact|door|window|leak|water leak|level|temperatura|humedad|movimiento|presencia|bater[ií]a|potencia|energ[ií]a|luz|estado|température|humidité|humidite|mouvement|présence|puissance|énergie|interrupteur|prise|lumière|lumiere|état|etat|porte|fenêtre|fenetre|fuite|niveau|umidità|umidita|movimento|presenza|batteria|potenza|energia|interruttore|presa|luce|stato|contatto|porta|finestra|perdita|livello|temperatuur|vochtigheid|luchtvochtigheid|beweging|aanwezigheid|batterij|vermogen|schakelaar|stopcontact|deur|raam|lek|umidade|presença|presenca|bateria|potência|interruptor|tomada|contato|janela|vazamento|nível|nivel|sıcaklık|sicaklik|sıcaklığı|sicakligi|nem|nemi|rutubet|doluluk|hareket|varlık|varlik|batarya|pil seviyesi|güç|guc|enerji|anahtar|priz|ışık|isik|durum|durumu|kontak|kapı|kapi|pencere|sızıntı|sizinti|su kaçağı|kacak|seviye|pil\b)$/i;

/** place_noise: 88 stems in de, en, es, fr, it, nl, pt-BR, tr. */
export const PLACE_NOISE = /\b(klima|sensor|sensoren|temperatur|luftfeuchtigkeit|thermostat|der|die|das|im|in|sensors|temperature|humidity|clima|sensores|temperatura|humedad|termostato|de|del|la|el|climat|capteur|capteurs|température|humidité|humidite|du|le|les|des|sensore|sensori|umidità|umidita|di|della|il|i|klimaat|temperatuur|vochtigheid|thermostaat|het|van|umidade|da|do|a|o|no|na|sensör|sensörü|sensoru|sıcaklık|sicaklik|sıcaklığı|sicakligi|nem|nemi|termostat)\b/gi;
