import { readdir, readFile, writeFile } from 'node:fs/promises';
import { basename, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { format, resolveConfig } from 'prettier';
import { derivePalette } from '../src/build/derive.js';
import { buildReports } from '../src/emit/contrast.js';
import { paletteFileName, parsePaletteFile, type PaletteFile } from '../src/palettes/file.js';
import { seedOf } from '../src/runtime.js';

/*
 * The community palettes' index, generated from the files in `src/palettes/community/`: every file must parse,
 * be named after its `name`, be the only one of that name, and pass the palette gates in both modes (a vivid
 * palette's accent chroma is its author's choice, and that gate is left to them). `pnpm build` writes the index;
 * CI refuses a change to the files that forgot to rebuild it.
 */

const DIR = join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'palettes', 'community');
const OUT = join(DIR, 'index.ts');
const THEIRS = /accent-chroma/;

async function main(): Promise<void> {
  const names = (await readdir(DIR)).filter((file) => file.endsWith('.fluvy-palette.json')).sort();
  const files: PaletteFile[] = [];
  for (const entry of names) {
    const file = parsePaletteFile(JSON.parse(await readFile(join(DIR, entry), 'utf8')));
    if (!file) throw new Error(`${entry}: not a well-formed palette file`);
    if (paletteFileName(file) !== basename(entry))
      throw new Error(`${entry}: its name is "${file.name}" (the file is named after it)`);
    if (files.some((other) => other.name === file.name))
      throw new Error(`${entry}: a palette named "${file.name}" is already in the set`);
    const palette = derivePalette(seedOf(file.palette));
    const failed = buildReports([palette]).flatMap((report) => [
      ...report.contrast
        .filter((gate) => !gate.pass && !THEIRS.test(gate.id))
        .map((gate) => `${report.mode} ${gate.id}`),
      ...report.structural
        .filter((gate) => !gate.pass && !THEIRS.test(gate.id))
        .map((gate) => `${report.mode} ${gate.id}`),
    ]);
    if (failed.length) throw new Error(`${entry}: fails ${failed.join(', ')}`);
    files.push(file);
  }
  const code = `// Generated by scripts/community.ts from the files beside it — do not edit; add a file and rebuild.
import type { PaletteFile } from '../file.js';

/** The palettes shared with every house, in the order of their names. */
export const COMMUNITY_PALETTES: readonly PaletteFile[] = ${JSON.stringify(files, null, 2)};
`;
  const options = (await resolveConfig(OUT)) ?? {};
  await writeFile(OUT, await format(code, { ...options, filepath: OUT }), 'utf8');
  console.log(`community palettes: ${files.map((file) => file.name).join(', ')}`);
}

await main();
