import {
  addElementDialogCss,
  addFromTargetCss,
  automationRowCss,
  nestedBlockCss,
  settingsRowCss,
  editorPageCss,
  emptyPickerCss,
  manualEditorCss,
  overflowShortcutCss,
  rowListCss,
  rowTargetsCss,
  saveFabCss,
  sceneSaveFabCss,
  serviceControlCss,
  sidebarCardCss,
  sidebarCss as automationSidebarCss,
} from './css/automation.js';
import { drawerCss, frameCss, sidebarCss, sidebarIconsCss } from './css/chrome.js';
import {
  cardEditCss,
  editBarCss,
  gridSectionAddCss,
  sectionEditCss,
  sectionsViewCss,
  viewBadgesCss,
  viewHeaderCss,
} from './css/dashboard.js';
import {
  assistChipCss,
  buttonCss,
  checkListItemCss,
  filterChipCss,
  filterPaneChipCss,
  booleanSelectorCss,
  checkboxCss,
  formGridCss,
  genericPickerCss,
  radioCss,
  radioGroupCss,
  sliderCss,
  toggleGroupCss,
} from './css/controls.js';
import {
  alertCss,
  automationSaveDialogCss,
  bottomSheetCss,
  cardPickerCss,
  dashboardCardCss,
  datePickerCss,
  dialogCss,
  dialogFooterCss,
  dialogHeaderCss,
  editCardDialogCss,
  newAutomationDialogCss,
  newDashboardDialogCss,
  resizableSheetCss,
  waDialogCss,
} from './css/dialogs.js';
import {
  boxedField,
  codeEditorCss,
  formStack,
  inputCss,
  outlinedFieldCss,
  pickerFieldCss,
  textareaCss,
  timeInputCss,
} from './css/fields.js';
import { comboItemCss, rowSupportingCss, sectionTitleCss } from './css/lists.js';
import { dropdownCss, dropdownItemCss, pickerListCss, quickBarCss } from './css/menus.js';
import {
  buttonGroupCss,
  entitySettingsEditorCss,
  listItemCss,
  mediaPlayerCss,
  pairedFooterCss,
  selectContainerCss,
  weatherCss,
} from './css/more-info.js';
import { headerBarCss, notificationItemCss, notificationsCss } from './css/notifications.js';
import { pageCss } from './css/page.js';
import { wallDashboardCss, wallDrawerCss, wallPageCss } from './css/wall.js';
import {
  dateRangeNavCss,
  debugViewportCss,
  errorLogCss,
  historyPanelCss,
  logbookCardCss,
  logbookPanelCss,
  mediaBarCss,
  mediaBrowseCss,
  moreInfoLogbookCss,
  todoListCardCss,
  todoPanelCss,
  viewPanelCss,
} from './css/panels.js';
import {
  appCardCss,
  appsGridCss,
  areaPageCss,
  areasCss,
  assistPrefCss,
  backupRetentionCss,
  backupDataCss,
  backupScheduleCss,
  backupSettingsCss,
  brandImageCss,
  brandImageSmallCss,
  cardActionsCss,
  cardHeaderCss,
  cloudDiscoverCss,
  configDashboardCss,
  configListCss,
  configSectionCss,
  contentGutterCss,
  deviceEntitiesCardCss,
  devicePageCss,
  energyConfigCss,
  energySettingsCss,
  entryRowCss,
  expansionPanelCss,
  formExpandableCss,
  gridSectionCss,
  haEmptyStateCss,
  hardwareCss,
  helperDialogCss,
  inputCopyCss,
  integrationActionCardCss,
  integrationHeaderCss,
  integrationsCss,
  logbookCss,
  logbookEmptyCss,
  logbookRendererCss,
  logCardCss,
  mapCss,
  mdListItemCss,
  moreInfoDialogCss,
  labsCss,
  networkAdapterCss,
  networkCss,
  scheduleFormCss,
  sceneEditorCss,
  filterPaneCss,
  pageSearchCss,
  panelTitleCss,
  profileSectionCss,
  sectionHeadingCss,
  segmentedBarCss,
  selectBoxCss,
  storageChartCss,
  storageSectionCss,
  themeSettingsCss,
  urlFormCss,
  voiceBrandCss,
  zonePageCss,
} from './css/settings.js';
import {
  dataTableCss,
  pageTitleCss,
  subpageCss,
  tablePageCss,
  tabCss,
  tabsSubpageCss,
} from './css/tables.js';

/**
 * One stylesheet of the shell and where it goes.
 *
 * `target` is `'document'` or the tag of a Home Assistant element (custom element tags always contain a
 * dash, so the two never collide). A tag's sheet is added to its Lit class's `elementStyles`: every
 * instance adopts it, including those created later. Subclasses keep their own `elementStyles`, so
 * every tag is listed on its own.
 */
export interface ShellSheet {
  /** Names the sheet in `report()`. */
  readonly id: string;
  readonly target: string;
  readonly css: string;
  /** A selector expected in the target's shadow root while it is on screen: `report()` tells whether Home Assistant still draws it. */
  readonly probe?: string;
  /**
   * A selector whose presence means the probe is not expected: one of our pages stands in the panel's place, so
   * Home Assistant draws nothing of its own to style. Without it a taken-over panel would read as a regression.
   */
  readonly instead?: string;
  /**
   * A choice the house can turn off: `icons`, our icons in Home Assistant's own menus (the sidebar's glyphs,
   * Settings' icon circles) — off, the sheet stays empty and Home Assistant draws its own. `wall`: the sheet fills
   * only while `<html>` carries the wall attribute, and then whatever the theme.
   */
  readonly choice?: 'icons' | 'wall';
}

/** Every touch of the shell. Adding a Home Assistant component is one line here plus its CSS in `css/`. */
export const SHEETS: readonly ShellSheet[] = [
  // the page and the chrome
  { id: 'page', target: 'document', css: pageCss },
  { id: 'frame', target: 'home-assistant', css: frameCss, probe: 'home-assistant-main' },
  { id: 'drawer', target: 'ha-drawer', css: drawerCss, probe: '.sidebar-shell' },
  { id: 'sidebar', target: 'ha-sidebar', css: sidebarCss, probe: 'ha-list-item-button' },
  { id: 'sidebar-icons', target: 'ha-sidebar', css: sidebarIconsCss, choice: 'icons' },
  { id: 'subpage', target: 'hass-subpage', css: subpageCss, probe: '.main-title' },
  { id: 'tabs-subpage', target: 'hass-tabs-subpage', css: tabsSubpageCss, probe: '.toolbar' },
  { id: 'tab', target: 'ha-tab', css: tabCss },
  { id: 'top-app-bar', target: 'ha-top-app-bar-fixed', css: pageTitleCss, probe: '.title' },
  {
    id: 'two-pane-app-bar',
    target: 'ha-two-pane-top-app-bar-fixed',
    css: pageTitleCss,
    probe: '.title',
  },
  { id: 'dashboard-root', target: 'hui-root', css: `${subpageCss}\n${editBarCss}` },
  // a wall panel: no chrome (fills on `<html fluvy-wall>` alone)
  { id: 'wall:page', target: 'document', css: wallPageCss, choice: 'wall' },
  {
    id: 'wall:drawer',
    target: 'ha-drawer',
    css: wallDrawerCss,
    probe: '.sidebar-shell',
    choice: 'wall',
  },
  {
    id: 'wall:dashboard',
    target: 'hui-root',
    css: wallDashboardCss,
    probe: '.header',
    choice: 'wall',
  },
  { id: 'view-header', target: 'hui-view-header', css: viewHeaderCss },
  { id: 'view-badges', target: 'hui-view-badges', css: viewBadgesCss },
  { id: 'section-edit', target: 'hui-section-edit-mode', css: sectionEditCss },
  { id: 'card-edit', target: 'hui-card-edit-mode', css: cardEditCss },
  { id: 'sections-view', target: 'hui-sections-view', css: sectionsViewCss },
  // notifications
  {
    id: 'notifications',
    target: 'notification-drawer',
    css: notificationsCss,
    probe: 'ha-header-bar',
  },
  { id: 'header-bar', target: 'ha-header-bar', css: headerBarCss },
  {
    id: 'notification',
    target: 'notification-item-template',
    css: notificationItemCss,
    probe: 'ha-card',
  },
  // cards and titles
  { id: 'card', target: 'ha-card', css: `${cardHeaderCss}\n${cardActionsCss}` },
  {
    id: 'config-list',
    target: 'ha-config-navigation-list',
    css: configListCss,
    probe: '.icon-background',
    choice: 'icons',
  },
  {
    id: 'config-info',
    target: 'ha-config-info',
    css: configListCss,
    probe: '.icon-background',
    choice: 'icons',
  },
  {
    id: 'restart-dialog',
    target: 'dialog-restart',
    css: configListCss,
    probe: '.icon-background',
    choice: 'icons',
  },
  { id: 'config-section', target: 'ha-config-section', css: configSectionCss },
  {
    id: 'config-dashboard',
    target: 'ha-config-dashboard',
    css: configDashboardCss,
    probe: 'ha-card',
  },
  {
    id: 'heading:system-log-card',
    target: 'system-log-card',
    css: `${sectionHeadingCss}\n${logCardCss}`,
    probe: '.header',
  },
  {
    id: 'heading:error-log-card',
    target: 'error-log-card',
    css: `${sectionHeadingCss}\n${errorLogCss}\n${logCardCss}`,
    probe: '.header',
  },
  ...[
    'ha-energy-grid-settings',
    'ha-energy-solar-settings',
    'ha-energy-battery-settings',
    'ha-energy-gas-settings',
    'ha-energy-water-settings',
    'ha-energy-device-settings',
    'ha-energy-device-settings-water',
    'ha-backup-summary-card',
    'ha-config-section-updates',
    'ha-config-repairs-dashboard',
  ].map((tag): ShellSheet => ({
    id: `heading:${tag}`,
    target: tag,
    css: tag.startsWith('ha-energy-')
      ? `${sectionHeadingCss}\n${energySettingsCss}`
      : sectionHeadingCss,
  })),
  {
    id: 'hardware',
    target: 'ha-config-hardware-overview',
    css: `${sectionHeadingCss}\n${hardwareCss}`,
    probe: '.header .title',
  },
  // tables
  {
    id: 'data-table',
    target: 'ha-data-table',
    css: dataTableCss,
    probe: '.mdc-data-table__content',
  },
  {
    id: 'table-page',
    target: 'hass-tabs-subpage-data-table',
    css: tablePageCss,
    probe: 'ha-data-table',
  },
  // fields
  { id: 'input', target: 'ha-input', css: `${inputCss}\n${outlinedFieldCss}`, probe: 'wa-input' },
  {
    id: 'input-search',
    target: 'ha-input-search',
    css: `${inputCss}\n${outlinedFieldCss}`,
    probe: 'wa-input',
  },
  { id: 'textarea', target: 'ha-textarea', css: textareaCss },
  {
    id: 'picker-field',
    target: 'ha-picker-field',
    css: pickerFieldCss,
    probe: 'ha-combo-box-item',
  },
  {
    id: 'labels',
    target: 'ha-labels-picker',
    css: boxedField('ha-chip-set'),
    probe: 'ha-chip-set',
  },
  {
    id: 'entity-name',
    target: 'ha-entity-name-picker',
    css: boxedField('.field'),
    probe: '.field',
  },
  {
    id: 'state-content',
    target: 'ha-entity-state-content-picker',
    css: boxedField('.container'),
    probe: '.container',
  },
  {
    id: 'clock-format',
    target: 'ha-clock-date-format-picker',
    css: boxedField('.container'),
    probe: '.container',
  },
  { id: 'time', target: 'ha-base-time-input', css: timeInputCss },
  { id: 'code-editor', target: 'ha-code-editor', css: codeEditorCss },
  // menus and lists
  { id: 'menu', target: 'ha-dropdown', css: dropdownCss, probe: '#menu' },
  { id: 'menu-item', target: 'ha-dropdown-item', css: dropdownItemCss, probe: '#label' },
  {
    id: 'picker-list',
    target: 'ha-picker-combo-box',
    css: pickerListCss,
    probe: 'lit-virtualizer',
  },
  { id: 'combo-item', target: 'ha-combo-box-item', css: comboItemCss },
  { id: 'quick-bar', target: 'ha-quick-bar', css: quickBarCss },
  { id: 'section-title', target: 'ha-section-title', css: sectionTitleCss },
  ...[
    'ha-row-item',
    'ha-list-item-base',
    'ha-list-item-button',
    'ha-list-item-option',
    'ha-list-item-value',
  ].map((tag): ShellSheet => ({ id: `row:${tag}`, target: tag, css: rowSupportingCss })),
  { id: 'check-list-item', target: 'ha-check-list-item', css: checkListItemCss },
  { id: 'md-list-item', target: 'ha-md-list-item', css: mdListItemCss },
  // controls
  { id: 'radio', target: 'ha-radio-option', css: radioCss, probe: '.control' },
  { id: 'checkbox', target: 'ha-checkbox', css: checkboxCss },
  { id: 'radio-group', target: 'ha-radio-group', css: radioGroupCss },
  { id: 'boolean-selector', target: 'ha-selector-boolean', css: booleanSelectorCss },
  { id: 'form-grid', target: 'ha-form-grid', css: formGridCss },
  { id: 'generic-picker', target: 'ha-generic-picker', css: genericPickerCss },
  { id: 'dialog', target: 'ha-dialog', css: dialogCss },
  { id: 'bottom-sheet', target: 'ha-bottom-sheet', css: bottomSheetCss },
  { id: 'dialog-footer', target: 'ha-dialog-footer', css: dialogFooterCss },
  { id: 'edit-card-dialog', target: 'hui-dialog-edit-card', css: editCardDialogCss },
  { id: 'card-picker', target: 'hui-card-picker', css: cardPickerCss },
  { id: 'dashboard-card', target: 'dashboard-card', css: dashboardCardCss },
  { id: 'new-dashboard', target: 'ha-dialog-new-dashboard', css: newDashboardDialogCss },
  // creation forms: one 16 rhythm (the schedule's week also loses its default yellow)
  ...[
    'ha-input_boolean-form',
    'ha-input_button-form',
    'ha-input_datetime-form',
    'ha-input_number-form',
    'ha-input_select-form',
    'ha-input_text-form',
    'ha-counter-form',
    'ha-timer-form',
    'ha-schedule-form',
    'dialog-label-detail',
    'dialog-tag-detail',
    'dialog-person-detail',
    'dialog-area-registry-detail',
    'dialog-floor-registry-detail',
  ].map((tag): ShellSheet => ({
    id: `form-stack:${tag}`,
    target: tag,
    css:
      tag === 'ha-schedule-form' ? `${formStack('.form')}\n${scheduleFormCss}` : formStack('.form'),
  })),
  { id: 'wa-dialog', target: 'wa-dialog', css: waDialogCss },
  { id: 'automation-save', target: 'ha-dialog-automation-save', css: automationSaveDialogCss },
  { id: 'date-picker', target: 'ha-dialog-date-picker', css: datePickerCss },
  { id: 'resizable-sheet', target: 'ha-resizable-bottom-sheet', css: resizableSheetCss },
  { id: 'settings-row', target: 'ha-settings-row', css: settingsRowCss },
  ...['ha-automation-action-if', 'ha-automation-option-row'].map((tag): ShellSheet => ({
    id: `nested-block:${tag}`,
    target: tag,
    css: nestedBlockCss,
  })),
  { id: 'scene-editor', target: 'ha-scene-editor', css: sceneEditorCss },
  ...[
    'ha-filter-devices',
    'ha-filter-domains',
    'ha-filter-entities',
    'ha-filter-entity-types',
    'ha-filter-integrations',
    'ha-filter-labels',
  ].map((tag): ShellSheet => ({ id: `filter-search:${tag}`, target: tag, css: filterPaneCss })),
  {
    id: 'helper-tab',
    target: 'entity-settings-helper-tab',
    css: `${pairedFooterCss}\n.buttons { border-top: 1px solid var(--divider-color); }`,
  },
  { id: 'slider', target: 'ha-slider', css: sliderCss, probe: '#thumb' },
  { id: 'button', target: 'ha-button', css: buttonCss },
  {
    id: 'toggle-group',
    target: 'ha-button-toggle-group',
    css: toggleGroupCss,
    probe: 'wa-button-group',
  },
  { id: 'filter-chip', target: 'ha-filter-chip', css: filterChipCss },
  { id: 'filter-pane-chip', target: 'ha-filter-pane-chip', css: filterPaneChipCss },
  { id: 'assist-chip', target: 'ha-assist-chip', css: assistChipCss },
  { id: 'select-box', target: 'ha-select-box', css: selectBoxCss, probe: '.option' },
  { id: 'expansion-panel', target: 'ha-expansion-panel', css: expansionPanelCss },
  { id: 'form-expandable', target: 'ha-form-expandable', css: formExpandableCss },
  // dialogs
  { id: 'dialog-header', target: 'ha-dialog-header', css: dialogHeaderCss, probe: '.header-title' },
  { id: 'alert', target: 'ha-alert', css: alertCss, probe: '.issue-type' },
  { id: 'new-automation', target: 'ha-dialog-new-automation', css: newAutomationDialogCss },
  { id: 'helper-dialog', target: 'dialog-helper-detail', css: helperDialogCss },
  { id: 'more-info', target: 'ha-more-info-dialog', css: moreInfoDialogCss, probe: '.content' },
  {
    id: 'more-info-logbook',
    target: 'ha-more-info-logbook',
    css: moreInfoLogbookCss,
    probe: 'ha-logbook',
  },
  {
    id: 'select-container',
    target: 'ha-more-info-control-select-container',
    css: selectContainerCss,
  },
  { id: 'button-group', target: 'ha-control-button-group', css: buttonGroupCss },
  { id: 'media-player', target: 'more-info-media_player', css: mediaPlayerCss },
  { id: 'weather', target: 'more-info-weather', css: weatherCss, probe: 'ha-tab-group' },
  { id: 'update-footer', target: 'more-info-update', css: pairedFooterCss, probe: '.actions' },
  {
    id: 'entity-settings-footer',
    target: 'entity-registry-settings',
    css: pairedFooterCss,
    probe: '.buttons',
  },
  {
    id: 'entity-settings',
    target: 'entity-registry-settings-editor',
    css: entitySettingsEditorCss,
    probe: '.menu-item',
  },
  { id: 'list-item', target: 'ha-list-item', css: listItemCss },
  { id: 'empty-state', target: 'ha-empty-state', css: haEmptyStateCss, probe: '.content' },
  // settings pages
  {
    id: 'integrations',
    target: 'ha-config-integrations-dashboard',
    css: `${sectionHeadingCss}\n${integrationsCss}`,
    probe: '.container',
  },
  { id: 'integration-header', target: 'ha-integration-header', css: integrationHeaderCss },
  {
    id: 'integration-action-card',
    target: 'ha-integration-action-card',
    css: integrationActionCardCss,
  },
  {
    id: 'device-entities-card',
    target: 'ha-device-entities-card',
    css: deviceEntitiesCardCss,
    probe: '.card-actions',
  },
  ...['ha-profile-section-general', 'ha-profile-section-security'].map((tag): ShellSheet => ({
    id: `profile:${tag}`,
    target: tag,
    css: profileSectionCss,
    probe: '.content',
  })),
  ...[
    'ha-config-lovelace-resources',
    'ha-config-info',
    'ha-config-repairs-dashboard',
    'ha-config-section-updates',
    'ha-config-section-analytics',
    'ha-config-section-storage',
    'ha-config-section-network',
    'ha-config-section-general',
    'ha-config-backup-overview',
    'ha-backup-overview-backups',
    'ha-config-backup-details',
    'ha-config-backup-location',
    'ha-config-backup-app-update-backups',
    'ha-backup-overview-settings',
    'ha-config-backup-settings',
    'ha-config-hardware-overview',
    'ha-config-voice-assistants-assistants',
  ].map((tag): ShellSheet => ({
    id: `gutter:${tag}`,
    target: tag,
    css: contentGutterCss,
    probe: '.content',
  })),
  { id: 'entry-row', target: 'ha-config-entry-row', css: entryRowCss },
  {
    id: 'device-page',
    target: 'ha-config-device-page',
    css: `${sectionHeadingCss}\n${devicePageCss}`,
  },
  { id: 'areas', target: 'ha-config-areas-dashboard', css: areasCss, probe: '.card-header' },
  { id: 'area-page', target: 'ha-config-area-page', css: areaPageCss },
  { id: 'logbook', target: 'ha-logbook', css: logbookCss },
  {
    id: 'logbook-renderer',
    target: 'ha-logbook-renderer',
    css: `${logbookRendererCss}\n${logbookEmptyCss}`,
  },
  { id: 'zone', target: 'ha-config-zone', css: zonePageCss },
  { id: 'segmented-bar', target: 'ha-segmented-bar', css: segmentedBarCss, probe: '.bar' },
  { id: 'storage-chart', target: 'storage-breakdown-chart', css: storageChartCss },
  { id: 'storage', target: 'ha-config-section-storage', css: storageSectionCss },
  { id: 'app-card', target: 'supervisor-apps-card-content', css: appCardCss },
  { id: 'apps-repository', target: 'supervisor-apps-repository', css: appsGridCss },
  { id: 'apps-installed', target: 'ha-config-apps-installed', css: appsGridCss },
  { id: 'backup-retention', target: 'ha-backup-config-retention', css: backupRetentionCss },
  { id: 'backup-schedule', target: 'ha-backup-config-schedule', css: backupScheduleCss },
  { id: 'map', target: 'ha-map', css: mapCss },
  { id: 'cloud-discover', target: 'cloud-discover', css: cloudDiscoverCss },
  { id: 'voice-brand', target: 'voice-assistant-brand-icon', css: voiceBrandCss, probe: 'img' },
  { id: 'assist-pref', target: 'assist-pref', css: assistPrefCss, probe: 'ha-list-item' },
  { id: 'network', target: 'supervisor-network', css: networkCss, probe: 'ha-expansion-panel' },
  { id: 'network-adapter', target: 'ha-network', css: networkAdapterCss },
  {
    id: 'labs',
    target: 'ha-config-labs',
    css: `${sectionHeadingCss}\n${labsCss}`,
    probe: '.card-actions',
  },
  { id: 'backup-data', target: 'ha-backup-config-data', css: backupDataCss },
  { id: 'backup-settings', target: 'ha-config-backup-settings', css: backupSettingsCss },
  { id: 'url-form', target: 'ha-config-url-form', css: urlFormCss },
  { id: 'input-copy', target: 'ha-input-copy', css: inputCopyCss, probe: '.textfield-container' },
  { id: 'theme-settings', target: 'ha-theme-settings', css: themeSettingsCss },
  { id: 'energy-config', target: 'ha-config-energy', css: energyConfigCss, probe: '.content' },
  { id: 'logs', target: 'ha-config-logs', css: pageSearchCss, probe: '.search' },
  { id: 'apps-store', target: 'ha-config-apps-available', css: pageSearchCss, probe: '.search' },
  { id: 'repairs', target: 'ha-config-repairs', css: brandImageCss },
  ...['ha-backup-config-agents', 'ha-backup-agents-picker'].map((tag): ShellSheet => ({
    id: `brand-image:${tag}`,
    target: tag,
    css: brandImageSmallCss,
  })),
  // automations and scripts
  ...['manual-automation-editor', 'manual-script-editor'].map((tag): ShellSheet => ({
    id: `editor:${tag}`,
    target: tag,
    css: `${manualEditorCss}\n${saveFabCss}`,
  })),
  ...['blueprint-automation-editor', 'blueprint-script-editor'].map((tag): ShellSheet => ({
    id: `save:${tag}`,
    target: tag,
    css: saveFabCss,
  })),
  { id: 'save:ha-scene-editor', target: 'ha-scene-editor', css: sceneSaveFabCss },
  ...[
    'ha-automation-trigger',
    'ha-automation-condition',
    'ha-automation-action',
    'ha-automation-option',
  ].map((tag): ShellSheet => ({ id: `rows:${tag}`, target: tag, css: rowListCss })),
  ...[
    'ha-automation-trigger-row',
    'ha-automation-condition-row',
    'ha-automation-action-row',
    'ha-automation-option-row',
    'ha-script-field-row',
    'ha-automation-sidebar-trigger',
    'ha-automation-sidebar-condition',
    'ha-automation-sidebar-action',
    'ha-automation-sidebar-option',
    'ha-automation-sidebar-script-field',
  ].map((tag): ShellSheet => ({ id: `shortcuts:${tag}`, target: tag, css: overflowShortcutCss })),
  { id: 'add-from-target', target: 'ha-automation-add-from-target', css: addFromTargetCss },
  { id: 'add-element-dialog', target: 'add-automation-element-dialog', css: addElementDialogCss },
  ...['ha-automation-editor', 'ha-script-editor'].map((tag): ShellSheet => ({
    id: `editor-page:${tag}`,
    target: tag,
    css: editorPageCss,
  })),
  { id: 'automation-sidebar-card', target: 'ha-automation-sidebar-card', css: sidebarCardCss },
  { id: 'automation-sidebar', target: 'ha-automation-sidebar', css: automationSidebarCss },
  { id: 'automation-row', target: 'ha-automation-row', css: automationRowCss, probe: '.row' },
  { id: 'row-targets', target: 'ha-automation-row-targets', css: rowTargetsCss },
  { id: 'service-control', target: 'ha-service-control', css: serviceControlCss },
  ...['ha-automation-picker', 'ha-script-picker', 'ha-scene-dashboard'].map((tag): ShellSheet => ({
    id: `empty:${tag}`,
    target: tag,
    css: emptyPickerCss,
  })),
  // panels
  { id: 'logbook-card', target: 'hui-logbook-card', css: logbookCardCss },
  { id: 'logbook-panel', target: 'ha-panel-logbook', css: logbookPanelCss },
  { id: 'history-panel', target: 'ha-panel-history', css: historyPanelCss },
  { id: 'date-range-nav', target: 'ha-date-range-nav', css: dateRangeNavCss },
  { id: 'light-panel', target: 'ha-panel-light', css: viewPanelCss },
  { id: 'climate-panel', target: 'ha-panel-climate', css: viewPanelCss },
  { id: 'todo-panel', target: 'ha-panel-todo', css: todoPanelCss },
  ...(
    [
      ['ha-panel-history', 'fluvy-history'],
      ['ha-panel-media-browser', ''],
    ] as const
  ).map(([tag, ours]): ShellSheet => ({
    id: `panel-title:${tag}`,
    target: tag,
    css: panelTitleCss,
    probe: '.page-title',
    ...(ours ? { instead: ours } : {}),
  })),
  { id: 'todo-list-card', target: 'hui-todo-list-card', css: todoListCardCss },
  { id: 'debug-viewport', target: 'ha-debug-viewport-environment-card', css: debugViewportCss },
  { id: 'media-bar', target: 'ha-bar-media-player', css: mediaBarCss },
  { id: 'media-browse', target: 'ha-media-player-browse', css: mediaBrowseCss },
  {
    id: 'grid-section',
    target: 'hui-grid-section',
    css: `${gridSectionCss}\n${gridSectionAddCss}`,
  },
];
