import { createStrings } from '@fluvy/core';

/** Labels only this card uses. Words several cards share live in `@fluvy/core` (`en.ts` / `es.ts`). */
export const s = createStrings({
  en: {
    timeline: 'Timeline',
    no_calendar: 'Choose a calendar',
    unavailable: 'Calendar unavailable',
    off: 'Unavailable',
    failed: 'Could not load events',
    one_unavailable: '{name} is unavailable',
    some_unavailable: '{count} calendars are unavailable',
    untitled: 'No title',
    day_label: '{weekday} {day}',
    first_at: 'first at {time}',
    until: 'Until {time}',
    left: '{count} left',
    left_one: '1 left',
    badge_left: '{count} left',
    badge_left_one: '1 left',
    all_day_top: 'All',
    all_day_bottom: 'day',
    in_minutes: 'In {minutes} min',
    in_hours: 'In {hours} h',
    in_hours_minutes: 'In {hours} h {minutes} min',
    more: '+{count} more',
    earlier: '{count} earlier',
    previous_month: 'Previous month',
    next_month: 'Next month',
    editor_view: 'View',
    editor_tile: 'Tile',
    editor_tones: 'Tone of each calendar (entity: tone)',
    editor_first_weekday: 'Week starts on',
    editor_start_hour: 'Timeline from (hour)',
    editor_end_hour: 'Timeline to (hour)',
  },
  es: {
    timeline: 'Cronología',
    no_calendar: 'Elige un calendario',
    unavailable: 'Calendario no disponible',
    off: 'No disponible',
    failed: 'No se pudieron cargar los eventos',
    one_unavailable: '{name} no está disponible',
    some_unavailable: '{count} calendarios no están disponibles',
    untitled: 'Sin título',
    day_label: '{weekday} {day}',
    first_at: 'el primero a las {time}',
    until: 'Hasta las {time}',
    left: 'quedan {count}',
    left_one: 'queda 1',
    badge_left: 'Quedan {count}',
    badge_left_one: 'Queda 1',
    all_day_top: 'Todo',
    all_day_bottom: 'el día',
    in_minutes: 'En {minutes} min',
    in_hours: 'En {hours} h',
    in_hours_minutes: 'En {hours} h {minutes} min',
    more: '+{count} más',
    earlier: '{count} anteriores',
    previous_month: 'Mes anterior',
    next_month: 'Mes siguiente',
    editor_view: 'Vista',
    editor_tile: 'Tesela',
    editor_tones: 'Tono de cada calendario (entidad: tono)',
    editor_first_weekday: 'La semana empieza el',
    editor_start_hour: 'Cronología desde (hora)',
    editor_end_hour: 'Cronología hasta (hora)',
  },
});
