import { createStrings } from '@fluvy/core';
import { PAGE_WORDS } from '../shared/page-words.js';

/** The Activity view's words. */
export const s = createStrings({
  en: {
    ...PAGE_WORDS.en,
    title: 'Activity',
    'filter.highlights': 'Highlights',
    'filter.all': 'Everything',
    'filter.lights': 'Lights',
    'filter.climate': 'Climate',
    'filter.media': 'Media',
    'filter.security': 'Security',
    'filter.people': 'People',
    'filter.automations': 'Automations',
    'filter.devices': 'Devices',
    'filter.system': 'System',
    search: 'Search activity',
    search_short: 'Search',
    narrowed: 'Only {what}',
    changes_one: '{n} change',
    changes: '{n} changes',
    automations_one: '{n} automation run',
    automations: '{n} automation runs',
    restarts_one: '{n} restart',
    restarts: '{n} restarts',
    restart: 'Home Assistant restarted',
    burst: '{n} changes in {m} min',
    burst_short: '{n} changes in under a minute',
    repeat: '{n} changes',
    show_all: 'Show all {n}',
    new_one: '{n} new',
    new: '{n} new',
    empty: 'Nothing happened this day',
    empty_period: 'Nothing happened in this period',
    no_match: 'Nothing matches',
    show_everything: 'Show everything',
    more_info: 'More info',
    history: 'History',
    only_this: 'Only this',
    device: 'Device',
    from: 'From',
    to: 'To',
    day_start: 'Start of the day',
    'kind.automation': 'Automation',
    'kind.script': 'Script',
    'kind.person': 'Person',
    'kind.service': 'Action',
    'kind.entity': 'Device',
    rail: 'Time of day',
    loading: 'Loading the activity',
    'fact.when': 'When',
    'fact.change': 'Change',
    'fact.cause': 'Cause',
    'fact.trigger': 'Trigger',
    'fact.where': 'Where',
    trace: 'Traces',
    started: 'Started',
    stopped: 'Stopped',
    'msg.pressed': 'Pressed',
    'msg.activated': 'Activated',
    'msg.scanned': 'Scanned',
    'msg.updated': 'Updated',
    'msg.sent': 'Sent',
    'msg.detected': 'Detected',
    'msg.ran': 'Ran',
    'msg.command_sent': 'Command sent',
    'msg.event': 'Event detected',
    'msg.triggered': 'Triggered',
    trigger: 'Trigger: {what}',
    'trigger.numeric_state_of': 'numeric state of',
    'trigger.state_of': 'state of',
    'trigger.event': 'event',
    'trigger.time_pattern': 'time pattern',
    'trigger.time': 'time',
    'trigger.homeassistant_stopping': 'Home Assistant stopping',
    'trigger.homeassistant_starting': 'Home Assistant starting',
  },
  es: {
    ...PAGE_WORDS.es,
    title: 'Actividad',
    'filter.highlights': 'Destacados',
    'filter.all': 'Todo',
    'filter.lights': 'Luces',
    'filter.climate': 'Clima',
    'filter.media': 'Multimedia',
    'filter.security': 'Seguridad',
    'filter.people': 'Personas',
    'filter.automations': 'Automatizaciones',
    'filter.devices': 'Dispositivos',
    'filter.system': 'Sistema',
    search: 'Buscar en la actividad',
    search_short: 'Buscar',
    narrowed: 'Solo {what}',
    changes_one: '{n} cambio',
    changes: '{n} cambios',
    automations_one: '{n} ejecución',
    automations: '{n} ejecuciones',
    restarts_one: '{n} reinicio',
    restarts: '{n} reinicios',
    restart: 'Home Assistant se reinició',
    burst: '{n} cambios en {m} min',
    burst_short: '{n} cambios en menos de un minuto',
    repeat: '{n} cambios',
    show_all: 'Ver los {n}',
    new_one: '{n} nuevo',
    new: '{n} nuevos',
    empty: 'No pasó nada este día',
    empty_period: 'No pasó nada en este periodo',
    no_match: 'Nada coincide',
    show_everything: 'Ver todo',
    more_info: 'Más información',
    history: 'Historial',
    only_this: 'Solo este',
    device: 'Dispositivo',
    from: 'Desde',
    to: 'Hasta',
    day_start: 'Empieza el día',
    'kind.automation': 'Automatización',
    'kind.script': 'Script',
    'kind.person': 'Persona',
    'kind.service': 'Acción',
    'kind.entity': 'Dispositivo',
    rail: 'Hora del día',
    loading: 'Cargando la actividad',
    'fact.when': 'Cuándo',
    'fact.change': 'Cambio',
    'fact.cause': 'Causa',
    'fact.trigger': 'Disparador',
    'fact.where': 'Dónde',
    trace: 'Trazas',
    started: 'Se inició',
    stopped: 'Se detuvo',
    'msg.pressed': 'Pulsado',
    'msg.activated': 'Activada',
    'msg.scanned': 'Escaneada',
    'msg.updated': 'Actualizada',
    'msg.sent': 'Enviada',
    'msg.detected': 'Detectado',
    'msg.ran': 'Se ejecutó',
    'msg.command_sent': 'Orden enviada',
    'msg.event': 'Evento detectado',
    'msg.triggered': 'Se activó',
    trigger: 'Disparador: {what}',
    'trigger.numeric_state_of': 'valor de',
    'trigger.state_of': 'estado de',
    'trigger.event': 'evento',
    'trigger.time_pattern': 'patrón horario',
    'trigger.time': 'hora',
    'trigger.homeassistant_stopping': 'Home Assistant deteniéndose',
    'trigger.homeassistant_starting': 'Home Assistant iniciándose',
  },
});

export type ActivityString = Parameters<typeof s>[1];
